### ISSUE TITLE
Access Denied when using FindIT

### ISSUE THREAD

**Issue by phucty** [metapub/metapub#25]
I tried to get a pdf file for this document:
DOI: 10.1016/j.emc.2008.04.007
PubMed: 18655948

My code worked last month but this time I got the error as follows. Could you please help me resolve this problem?

`FindIt(doi="10.1016/j.emc.2008.04.007")`

```
Traceback (most recent call last):
  File "/home/phuc/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/metapub/findit/findit.py", line 147, in __init__
    self._load_pma_from_doi()
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/metapub/findit/findit.py", line 324, in _load_pma_from_doi
    self.pmid = doi2pmid(self.doi)
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/metapub/convert.py", line 132, in doi2pmid
    pmids = pm_fetch.pmids_for_query(doi)
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/metapub/pubmedfetcher.py", line 261, in _eutils_pmids_for_query
    result = self.qs.esearch({ 'db': 'pubmed', 'term': query,
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/eutils/_internal/queryservice.py", line 182, in esearch
    return self._query("/esearch.fcgi", args)
  File "/home/phuc/anaconda3/envs/py3/lib/python3.8/site-packages/eutils/_internal/queryservice.py", line 329, in _query
    raise EutilsRequestError("Access Denied: {url}".format(url=url))
eutils._internal.exceptions.EutilsRequestError: Access Denied: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?api_key=MY_NCB_API_KEY
```

**Comment by nthmost** [comment]
Hi @phucty,

Looks like you need to set your NCBI api key: the Access Denied is coming from NCBI.

> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?api_key=MY_NCB_API_KEY

[Check out this NCBI web page to read how to get one](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/).  When you have an API key, you should set it on the command line with:

`export NCBI_API_KEY=the_api_key_you_got_from_ncbi`
