### ISSUE TITLE
JSON DecodeError on Widows 10

### ISSUE THREAD

**Issue by nicthib** [metapub/metapub#42]
I have loved using metapub so far, but once I ported some code to my Windows 10 machine, I get this odd JSONDecodeError:

```
Traceback (most recent call last):
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 40 (char 39)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\metapub\findit\findit.py", line 147, in __init__
    self._load_pma_from_doi()
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\metapub\findit\findit.py", line 324, in _load_pma_from_doi
    self.pmid = doi2pmid(self.doi)
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\metapub\convert.py", line 132, in doi2pmid
    pmids = pm_fetch.pmids_for_query(doi)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\metapub\pubmedfetcher.py", line 261, in _eutils_pmids_for_query
    result = self.qs.esearch({ 'db': 'pubmed', 'term': query,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\eutils\_internal\queryservice.py", line 182, in esearch
    return self._query("/esearch.fcgi", args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\eutils\_internal\queryservice.py", line 310, in _query
    json = r.json()
           ^^^^^^^^
  File "C:\Users\dnt21\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting ',' delimiter: line 1 column 40 (char 39)
```

Seems like the request is truncated. Any ideas?

**Comment by nicthib** [comment]
Update: This error doesn't occur when I fail to provide an NCBI API key. Since I'm on Windows 10, I am setting it this way:

`set NCBI_API_KEY="API KEY"`

Is this not the right way to do it?
